apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-test-pvc-$(context.pipelineRun.name)
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi
