apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-test-pvc-$(params.pipelineRunName)
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi
